# Header
menu:
  首页: /
#  前端: /categories/front-end
#  后端: /categories/back-end
  标签: /tags
  归档: /archives
  订阅: /atom.xml
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Simon
  work: Golang,PHP Developer &amp; Designer
  location: Hefei, China
  avatar_url: /images/avatar.jpeg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/crcms
  - svg: ./source/svg/github.svg
    url: https://github.com/firmeve
#  - svg: ./source/svg/more.svg
#    url: http://weibo.com/sanonz
#  - svg: ./source/svg/twitter.svg
#    url: https://twitter.com/sanonze


# github comment 
git_commit:
  enable: true
  client_id: e1cbbb8b52f5de53cbce
  client_secret: 494fa22a9ca1b8d0a148ec8410e33eb1b08922bb
  repo: crcms.github.io
  owner: simon
  admin:
    - simon
  per_page: 10


# 百度统计
baidu:
  id: 2c09de12c175e88fd5cb35771db9e691

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.png
